Traceback (most recent call last):
  File "/home/olom/.vscode/extensions/ms-python.python-2021.9.1218897484/pythonFiles/shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/python3', '-m', 'pip', 'install']' returned non-zero exit status 1.
